services:
  app:
    image: ghcr.io/nsstoyanova22/rebank:latest
    pull_policy: always
    container_name: rebank-app
    restart: always
    env_file: .env
    networks:
      - shared-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8080/actuator/health || wget -q --spider http://127.0.0.1:8080/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    labels:
      caddy: rebank.oleksandr-vinichenko.xyz
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  shared-network:
    external: true
