CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS banks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL UNIQUE REFERENCES accounts(id),
    display_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    bank_id BIGINT NOT NULL REFERENCES banks(id),
    account_number VARCHAR(34) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    balance NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id BIGINT NOT NULL REFERENCES banks(id),
    name VARCHAR(120) NOT NULL,
    role VARCHAR(80) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_account_id BIGINT NOT NULL REFERENCES bank_accounts(id),
    counterparty_bank_account_id BIGINT REFERENCES bank_accounts(id),
    type VARCHAR(20) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    balance_after NUMERIC(19, 2) NOT NULL,
    description VARCHAR(200) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE bank_transactions
    ADD COLUMN IF NOT EXISTS bank_account_id BIGINT,
    ADD COLUMN IF NOT EXISTS counterparty_bank_account_id BIGINT;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'bank_transactions'
          AND column_name = 'account_id'
    ) THEN
        UPDATE bank_transactions txn
        SET bank_account_id = account_match.bank_account_id
        FROM (
            SELECT legacy.id AS transaction_id, bank_account.id AS bank_account_id
            FROM bank_transactions legacy
            JOIN clients client ON client.account_id = legacy.account_id
            JOIN LATERAL (
                SELECT id
                FROM bank_accounts
                WHERE client_id = client.id
                ORDER BY created_at, id
                LIMIT 1
            ) bank_account ON true
            WHERE legacy.bank_account_id IS NULL
        ) account_match
        WHERE txn.id = account_match.transaction_id;

        ALTER TABLE bank_transactions ALTER COLUMN account_id DROP NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'bank_transactions'
          AND column_name = 'counterparty_account_id'
    ) THEN
        UPDATE bank_transactions txn
        SET counterparty_bank_account_id = account_match.bank_account_id
        FROM (
            SELECT legacy.id AS transaction_id, bank_account.id AS bank_account_id
            FROM bank_transactions legacy
            JOIN clients client ON client.account_id = legacy.counterparty_account_id
            JOIN LATERAL (
                SELECT id
                FROM bank_accounts
                WHERE client_id = client.id
                ORDER BY created_at, id
                LIMIT 1
            ) bank_account ON true
            WHERE legacy.counterparty_bank_account_id IS NULL
        ) account_match
        WHERE txn.id = account_match.transaction_id;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM bank_transactions WHERE bank_account_id IS NULL) THEN
        ALTER TABLE bank_transactions ALTER COLUMN bank_account_id SET NOT NULL;
    END IF;
END $$;

DROP INDEX IF EXISTS idx_bank_transactions_account_created;
CREATE INDEX IF NOT EXISTS idx_bank_transactions_account_created
    ON bank_transactions (bank_account_id, created_at);
